language: julia

sudo: false

os:
  - linux
  - osx
  - windows

arch:
  - x64
  - x86

julia:
  - 1.0
  - 1
  - nightly

matrix:
  exclude:
    - os: osx
      arch: x86
  allow_failures:
  - julia: nightly

notifications:
  email: false

after_success:
   - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

branches:
  only:
  - master
  - gh-pages # For building documentation
  - /^testing-.*$/ # testing branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

cache:
  directories:
  - $HOME/.julia/artifacts
