name = "WorkerUtilities"
uuid = "76eceee3-57b5-4d4a-8e66-0e911cebbf60"
authors = ["Jacob Quinn <quinn.jacobd@gmail.com>"]
version = "1.6.1"

[deps]
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
