name = "WorkerUtilities"
uuid = "76eceee3-57b5-4d4a-8e66-0e911cebbf60"
authors = ["Jacob Quinn <quinn.jacobd@gmail.com>"]
version = "1.5.0"

[deps]

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

