name = "ConcurrentUtilities"
uuid = "f0e56b4a-5159-44fe-b623-3e5288b988bb"
authors = ["Jacob Quinn <quinn.jacobd@gmail.com>"]
version = "2.4.1"

[deps]
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[compat]
Serialization = "1.6"
Sockets = "1.6"
julia = "1.6"

[extras]
IOCapture = "b5f81e59-6552-4d32-b1f0-c071b021bf89"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["IOCapture", "Test"]
